definitions:
  entity.BusinessLoginOrRegisterRequest:
    properties:
      code:
        description: 验证码
        type: string
      tel:
        description: 手机号码
        type: string
    type: object
  entity.BusinessPassLoginRequest:
    properties:
      password:
        description: 密码
        type: string
      tel:
        description: 手机号码
        type: string
    type: object
  entity.ResponseData:
    properties:
      data:
        additionalProperties: true
        description: 返回数据
        type: object
      message:
        description: 提示信息
        type: string
      status:
        description: 成功失败标志；true：成功 、false：失败
        type: boolean
    type: object
  entity.SystemAdminLoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  entity.SystemAdminUpdatePassRequest:
    properties:
      new_password:
        description: 新密码
        type: string
      old_password:
        description: 旧密码
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/admin/admins/{ids}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account ID 多个用,分开
        in: path
        name: ids
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 批量删除管理员
      tags:
      - 系统管理员
  /api/v1/business/codelogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.BusinessLoginOrRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      summary: 商家手机验证码登录
      tags:
      - 商家
  /api/v1/business/passlogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.BusinessPassLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      summary: 商家账号密码登录
      tags:
      - 商家
  /api/v1/business/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.BusinessLoginOrRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      summary: 商家注册
      tags:
      - 商家
  /api/v1/business/store:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 查询商家门店信息
      tags:
      - 商家
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: 门店名称
        in: formData
        name: store_name
        required: true
        type: string
      - description: 门店详细地址
        in: formData
        name: store_address
        required: true
        type: string
      - description: 门店logo
        in: formData
        name: store_logo
        type: file
      - description: 门店联系人姓名
        in: formData
        name: store_contact_name
        type: string
      - description: 门店联系人电话
        in: formData
        name: store_contact_tel
        type: string
      - description: 门店开始营业时间
        in: formData
        name: store_start_banking_hours
        required: true
        type: string
      - description: 门店结束营业时间
        in: formData
        name: store_end_banking_hours
        required: true
        type: string
      - description: 门脸照
        in: formData
        name: store_face_photo
        type: file
      - description: 店内照
        in: formData
        name: in_store_photos
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 更新商家门店信息
      tags:
      - 商家
  /api/v1/common/verificationcode:
    get:
      consumes:
      - application/json
      parameters:
      - description: 手机号码
        in: query
        name: tel
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      summary: 获取验证码
      tags:
      - 公共接口
  /api/v1/system/admin:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 查询管理员by token
      tags:
      - 系统管理员
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 昵称
        in: formData
        name: nikename
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 操作权限 Y | N
        in: formData
        name: manager
        type: string
      - description: 用户头像
        in: formData
        name: avatar
        type: file
      - description: 是否启用
        in: formData
        name: is_enable
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 添加管理员
      tags:
      - 系统管理员
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: 昵称
        in: formData
        name: nikename
        type: string
      - description: 操作权限 Y | N
        in: formData
        name: manager
        type: string
      - description: 用户头像
        in: formData
        name: avatar
        type: file
      - description: 是否启用
        in: formData
        name: is_enable
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 修改管理员
      tags:
      - 系统管理员
  /api/v1/system/admin/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 删除管理员
      tags:
      - 系统管理员
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 查询管理员by id
      tags:
      - 系统管理员
  /api/v1/system/admin/enable/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: 启用/禁用管理员
        in: query
        name: is_enable
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 启用/禁用管理员
      tags:
      - 系统管理员
  /api/v1/system/admin/manager/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Y：授权/ N：禁止
        in: query
        name: is_manager
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 授权/禁止管理员权限
      tags:
      - 系统管理员
  /api/v1/system/admin/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.SystemAdminUpdatePassRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 修改管理员密码
      tags:
      - 系统管理员
  /api/v1/system/admins:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 创建开始时间
        in: query
        name: created_at_start
        type: string
      - description: 创建结束时间
        in: query
        name: created_at_end
        type: string
      - description: 操作权限
        in: query
        name: manager
        type: string
      - description: 创建人
        in: query
        name: created_by
        type: string
      - description: 是否启用
        in: query
        name: is_enable
        type: boolean
      - description: 页大小
        in: query
        name: pageSize
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 分页查询管理员(默认前100条) 并返回总记录数
      tags:
      - 系统管理员
  /api/v1/system/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.SystemAdminLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/entity.ResponseData'
      summary: 管理员登录
      tags:
      - 系统管理员
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
